import { bigint } from './bigint.ts';
import { bigintT } from './bigintT.ts';
import { boolean } from './boolean.ts';
import { bytes } from './bytes.ts';
import { customType } from './custom.ts';
import { dateDuration } from './date-duration.ts';
import { decimal } from './decimal.ts';
import { doublePrecision } from './double-precision.ts';
import { duration } from './duration.ts';
import { integer } from './integer.ts';
import { json } from './json.ts';
import { localDate } from './localdate.ts';
import { localTime } from './localtime.ts';
import { real } from './real.ts';
import { relDuration } from './relative-duration.ts';
import { smallint } from './smallint.ts';
import { text } from './text.ts';
import { timestamp } from './timestamp.ts';
import { timestamptz } from './timestamptz.ts';
import { uuid } from './uuid.ts';
export declare function getGelColumnBuilders(): {
    localDate: typeof localDate;
    localTime: typeof localTime;
    decimal: typeof decimal;
    dateDuration: typeof dateDuration;
    bigintT: typeof bigintT;
    duration: typeof duration;
    relDuration: typeof relDuration;
    bytes: typeof bytes;
    customType: typeof customType;
    bigint: typeof bigint;
    boolean: typeof boolean;
    doublePrecision: typeof doublePrecision;
    integer: typeof integer;
    json: typeof json;
    real: typeof real;
    smallint: typeof smallint;
    text: typeof text;
    timestamptz: typeof timestamptz;
    uuid: typeof uuid;
    timestamp: typeof timestamp;
};
export type GelColumnsBuilders = ReturnType<typeof getGelColumnBuilders>;
